#!/bin/bash -x
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
$NADO_VENV
python2.7 $OPENSHIFT_REPO_DIR/app.py
